import { PACKAGE_VERSION_PREFIX } from '../markers'
import type { PackageType } from '../package-type'
import { TYPE_RULES } from './type-rules'

export interface BuildPackageBodyArgs {
  /** CLI version that generated the block; recorded in the version line. */
  version: string
  /** Resolved package type; selects the `TYPE_RULES` entry and rides in the version line. */
  type: PackageType
  /** The package's `name` from `package.json`, rendered as the heading. */
  packageName: string
  /** Package directory relative to the repo root, posix-separated (e.g. `apps/client/ui`). */
  relDir: string
  /** Whether the package has a `README.md`. The bullet naming it is omitted when it does not. */
  hasReadme: boolean
  /**
   * Whether the package already has a `DESIGN.md`. Accepted for future use and
   * deliberately not rendered: the bullet appears for every `frontend` / `mobile`
   * package regardless, because it tells the agent what to do when the file is
   * absent (ask, do not invent one). Callers pass it so the body can react to it
   * later without a signature change.
   */
  hasDesign: boolean
}

/** The version line, e.g. `<!-- infra-kit:package:version 0.4.0 frontend -->`. */
const buildVersionLine = (version: string, type: PackageType): string => {
  return `${PACKAGE_VERSION_PREFIX}${version} ${type} -->`
}

const README_BULLET = '- `README.md` — what this package is and how to run it.'
const CONFIG_BULLET = '- `infra-kit.config.ts` — the audit rules this package must satisfy.'

const CHECK_BULLETS: readonly string[] = [
  '- `infra-kit audit` — validate this package against its infra-kit rules.',
  '- `pnpm run ts-check && pnpm run eslint-check && pnpm run test` — this package only.',
  '- `pnpm run qa` at the repo root — the full gate; run it before claiming completion.',
]

/**
 * Render a package's guidance body — the text that goes *between* the package
 * markers, version line first. The body never contains a marker itself; the
 * caller wraps it via `upsertManagedBlock`.
 *
 * Every type renders the same skeleton (heading, summary, Read first, Checks,
 * Rules) around its {@link TYPE_RULES} entry, and stays inside a 25-line budget
 * so a package block never crowds out the hand-authored text around it.
 *
 * @example
 * buildPackageBody({ version: '0.4.0', type: 'frontend', packageName: '@hulyo/client-ui',
 *   relDir: 'apps/client/ui', hasReadme: true, hasDesign: false })
 * // => '<!-- infra-kit:package:version 0.4.0 frontend -->\n\n# @hulyo/client-ui\n…'
 */
export const buildPackageBody = (args: BuildPackageBodyArgs): string => {
  const { version, type, packageName, relDir, hasReadme } = args
  const { label, firstReads, rules } = TYPE_RULES[type]

  const readFirst = [...(hasReadme ? [README_BULLET] : []), ...firstReads, CONFIG_BULLET]

  return [
    buildVersionLine(version, type),
    '',
    `# ${packageName}`,
    '',
    `Workspace package at \`${relDir}\` — type: **${label}**.`,
    'This block is generated by `infra-kit audit --fix` — edit text *outside* the markers, never inside.',
    '',
    '## Read first',
    '',
    ...readFirst,
    '',
    '## Checks',
    '',
    ...CHECK_BULLETS,
    '',
    '## Rules',
    '',
    ...rules,
  ].join('\n')
}
