import { describe, expect, it } from 'vitest'

import { checkClaudeInChrome } from '../doctor'
import type { ChromeCheckDeps } from '../doctor'

const HOME = '/home/dev'
const MANIFEST = `${HOME}/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.anthropic.claude_code_browser_extension.json`
const WRAPPER = `${HOME}/.claude/chrome/chrome-native-host`
const CLAUDE_BIN = `${HOME}/.local/bin/claude`

const manifest = JSON.stringify({ name: 'com.anthropic.claude_code_browser_extension', path: WRAPPER, type: 'stdio' })
const wrapper = `#!/bin/sh\n# Generated by Claude Code - do not edit manually\nexec ${CLAUDE_BIN} --chrome-native-host\n`

const run = (files: Record<string, string>, executables: string[], overrides: ChromeCheckDeps = {}) => {
  return checkClaudeInChrome({
    platform: 'darwin',
    home: HOME,
    readText: (filePath) => {
      return files[filePath] ?? null
    },
    isExecutable: (filePath) => {
      return executables.includes(filePath)
    },
    ...overrides,
  })
}

describe('checkClaudeInChrome', () => {
  it('passes when the native host is registered and its wrapper runs an existing claude', () => {
    const row = run({ [MANIFEST]: manifest, [WRAPPER]: wrapper }, [WRAPPER, CLAUDE_BIN])

    expect(row).toMatchObject({ name: 'claude in chrome', status: 'pass' })
    expect(row.message).toContain('/infra-kit:doctor')
  })

  it('warns, not fails, when Chrome was never set up', () => {
    expect(run({}, [])).toMatchObject({ status: 'warn', message: expect.stringContaining('/chrome') })
  })

  it('fails when the manifest is not JSON or names no host path', () => {
    expect(run({ [MANIFEST]: '{' }, []).status).toBe('fail')
    expect(run({ [MANIFEST]: '{"name":"x"}' }, []).status).toBe('fail')
  })

  it('fails when the wrapper is missing', () => {
    expect(run({ [MANIFEST]: manifest }, [])).toMatchObject({
      status: 'fail',
      message: expect.stringContaining('missing or not executable'),
    })
  })

  it('fails when the wrapper execs a claude binary that has moved', () => {
    expect(run({ [MANIFEST]: manifest, [WRAPPER]: wrapper }, [WRAPPER])).toMatchObject({
      status: 'fail',
      message: expect.stringContaining('no longer exists'),
    })
  })

  it('passes on a wrapper whose exec line it cannot read', () => {
    expect(run({ [MANIFEST]: manifest, [WRAPPER]: '#!/bin/sh\n' }, [WRAPPER]).status).toBe('pass')
  })

  it('reads the linux manifest location', () => {
    const linuxManifest = `${HOME}/.config/google-chrome/NativeMessagingHosts/com.anthropic.claude_code_browser_extension.json`

    expect(
      run({ [linuxManifest]: manifest, [WRAPPER]: wrapper }, [WRAPPER, CLAUDE_BIN], { platform: 'linux' }).status,
    ).toBe('pass')
  })

  it('skips on a platform with no known manifest location', () => {
    expect(run({}, [], { platform: 'win32' }).status).toBe('skip')
  })
})
