import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { writeAgentFiles } from 'src/commands/init/agent-files'
import { PACKAGE_MARKER_END, PACKAGE_MARKER_START, PACKAGE_VERSION_PREFIX } from 'src/lib/agent-guidance'
import { getProjectRoot, getRepoName } from 'src/lib/git-utils'
import { resetInfraKitConfigCache } from 'src/lib/infra-kit-config'

import packageJson from '../../../../package.json' with { type: 'json' }
import { checkAgentFiles } from '../doctor'

vi.mock('src/lib/git-utils', () => {
  return {
    getProjectRoot: vi.fn(),
    getRepoName: vi.fn(),
    // Mirror the real signature: with a linked-worktree-free test repo the main
    // root IS the given toplevel, so echo the passed cwd back.
    getMainRepoRoot: vi.fn(async (cwd?: string) => {
      return cwd
    }),
  }
})

const CURRENT_VERSION = packageJson.version

const writeFile = (filePath: string, content: string): void => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
}

/** A well-formed package guidance block recording `version` — what `inspectPackageGuidance` calls `ok`. */
const packageBlock = (version: string): string => {
  return [
    '# pkg',
    '',
    PACKAGE_MARKER_START,
    `${PACKAGE_VERSION_PREFIX}${version} lib -->`,
    'Guidance body.',
    PACKAGE_MARKER_END,
    '',
  ].join('\n')
}

/** Add a workspace package at `packages/<name>`, optionally carrying a guidance block. */
const addPackage = (repo: string, name: string, blockVersion: string | null): void => {
  const dir = path.join(repo, 'packages', name)

  writeFile(path.join(dir, 'package.json'), `{ "name": "${name}" }\n`)

  if (blockVersion !== null) writeFile(path.join(dir, 'CLAUDE.md'), packageBlock(blockVersion))
}

const withTmpRepo = async (fn: (tmp: string) => Promise<void>): Promise<void> => {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'infra-kit-doctor-staleness-test-'))

  vi.mocked(getProjectRoot).mockResolvedValue(tmp)
  vi.mocked(getRepoName).mockResolvedValue(path.basename(tmp))

  writeFile(path.join(tmp, 'infra-kit.json'), '{}\n')

  // getInfraKitConfigPaths memoizes on `cwd + homedir`, neither of which changes between
  // tests here (only the mocked getProjectRoot does), so the memo would hand this test the
  // PREVIOUS test's already-deleted tmp repo. Drop it on entry and exit.
  resetInfraKitConfigCache()

  try {
    await fn(tmp)
  } finally {
    resetInfraKitConfigCache()
    fs.rmSync(tmp, { recursive: true, force: true })
  }
}

const addWorkspaceFile = (repo: string): void => {
  writeFile(path.join(repo, 'pnpm-workspace.yaml'), "packages:\n  - 'packages/*'\n")
}

const messageOf = async (): Promise<string> => {
  const checks = await checkAgentFiles()

  expect(checks).toHaveLength(1)
  expect(checks[0]!.name).toBe('CLAUDE.md block')

  return checks[0]!.message
}

describe('checkAgentFiles package guidance staleness', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  afterEach(() => {
    vi.clearAllMocks()
  })

  it('reports blocks older than the running CLI without changing the pass status', async () => {
    await withTmpRepo(async (tmp) => {
      await writeAgentFiles()
      addWorkspaceFile(tmp)
      addPackage(tmp, 'alpha', '0.0.1')

      const checks = await checkAgentFiles()

      expect(checks[0]!.status).toBe('pass')
      expect(checks[0]!.message).toContain('CLAUDE.md block present')
      expect(checks[0]!.message).toContain(
        `1 package guidance blocks were generated by an older infra-kit (oldest 0.0.1, current ${CURRENT_VERSION})`,
      )
      expect(checks[0]!.message).toContain('infra-kit audit --fix --all')
    })
  })

  it('names the OLDEST stale version and counts only the stale blocks', async () => {
    await withTmpRepo(async (tmp) => {
      await writeAgentFiles()
      addWorkspaceFile(tmp)
      addPackage(tmp, 'alpha', '0.2.10')
      addPackage(tmp, 'beta', '0.0.9')
      addPackage(tmp, 'gamma', CURRENT_VERSION)
      // No CLAUDE.md at all — skipped, never counted as stale.
      addPackage(tmp, 'delta', null)

      const message = await messageOf()

      expect(message).toContain(
        `2 package guidance blocks were generated by an older infra-kit (oldest 0.0.9, current ${CURRENT_VERSION})`,
      )
    })
  })

  it('keeps the shipped root-block-absent failure, staleness suffix and all', async () => {
    await withTmpRepo(async (tmp) => {
      addWorkspaceFile(tmp)
      addPackage(tmp, 'alpha', '0.0.1')

      const checks = await checkAgentFiles()

      expect(checks[0]!.status).toBe('fail')
      expect(checks[0]!.message).toContain('Run: infra-kit init')
      expect(checks[0]!.message).toContain('1 package guidance blocks were generated by an older infra-kit')
    })
  })

  it('degrades to no staleness text when there is no pnpm-workspace.yaml', async () => {
    await withTmpRepo(async (tmp) => {
      await writeAgentFiles()
      addPackage(tmp, 'alpha', '0.0.1')

      const checks = await checkAgentFiles()

      expect(checks[0]!.status).toBe('pass')
      expect(checks[0]!.message).toBe('CLAUDE.md block present')
    })
  })

  it('degrades to no staleness text when pnpm-workspace.yaml is malformed', async () => {
    await withTmpRepo(async (tmp) => {
      await writeAgentFiles()
      writeFile(path.join(tmp, 'pnpm-workspace.yaml'), 'packages: [unclosed\n  - "packages/*"\n')
      addPackage(tmp, 'alpha', '0.0.1')

      const message = await messageOf()

      expect(message).toBe('CLAUDE.md block present')
    })
  })

  it('says nothing when every package block is at the running version', async () => {
    await withTmpRepo(async (tmp) => {
      await writeAgentFiles()
      addWorkspaceFile(tmp)
      addPackage(tmp, 'alpha', CURRENT_VERSION)

      const message = await messageOf()

      expect(message).toBe('CLAUDE.md block present')
      expect(message).not.toContain('older infra-kit')
    })
  })
})
