import fs from 'node:fs'
import path from 'node:path'

import { getInfraKitConfigPaths } from 'src/lib/infra-kit-config'
import { logger } from 'src/lib/logger'
import { hasManagedBlock, removeManagedBlock, upsertManagedBlock } from 'src/lib/managed-block'

import packageJson from '../../../package.json' with { type: 'json' }

/** Markers for the generated guidance block (HTML comments — invisible in rendered markdown). */
export const AGENTS_MARKER_START = '<!-- infra-kit:begin -->'
export const AGENTS_MARKER_END = '<!-- infra-kit:end -->'
/** The version line lives on its own line (OMC `OMC:VERSION:` precedent) so the markers stay constant-matchable. */
const AGENTS_VERSION_PREFIX = '<!-- infra-kit:version '

/**
 * Marker pair for the legacy `@AGENTS.md` import region once injected into CLAUDE.md.
 * Migration-only now: `writeAgentFiles` strips this region so the full guidance body
 * can take its place. TODO(remove after ~2 release cycles once repos have re-run init).
 */
export const AGENTS_IMPORT_START = '<!-- infra-kit:import:begin -->'
export const AGENTS_IMPORT_END = '<!-- infra-kit:import:end -->'

const AGENTS_FILE = 'AGENTS.md'
const CLAUDE_FILE = 'CLAUDE.md'

export type WriteAction = 'created' | 'updated' | 'unchanged' | 'removed'

export interface AgentFileWrite {
  path: string
  action: WriteAction
}

export interface WriteAgentFilesResult {
  /** True when run outside an infra-kit repo (no `infra-kit.json` at the git root). */
  skipped: boolean
  /** Repo root the files were written under, or null when skipped. */
  root: string | null
  written: AgentFileWrite[]
}

/** The version comment line, e.g. `<!-- infra-kit:version 0.1.105 -->`. */
const buildVersionLine = (version: string): string => {
  return `${AGENTS_VERSION_PREFIX}${version} -->`
}

/**
 * The generated guidance body (without the surrounding markers). Describes the
 * infra-kit CLI surface so any AI agent working in the repo learns it. Curated
 * from the real command set; the version line records which CLI version generated it.
 */
const buildAgentsBody = (version: string): string => {
  return [
    buildVersionLine(version),
    '',
    '# infra-kit',
    '',
    'This repository uses the **infra-kit** CLI for environment, worktree, and release workflows.',
    'This block is generated by `infra-kit init` — edit text *outside* the markers, never inside.',
    '',
    '## Commands (`ik` = `pnpm exec infra-kit`)',
    '',
    '- `ik env-load -c <config>` / `ik env-clear` / `ik env-status` — load, clear, or inspect Doppler env vars for a config (e.g. `dev`). Source the returned file to apply.',
    '- `ik worktrees add` / `worktrees list` / `worktrees reload` / `worktrees remove` / `worktrees sync` — manage release and feature git worktrees.',
    '- `ik release create` / `release list` / `release deploy-all` / `release deploy-selected` / `release deliver` / `release desc-edit` — release-branch and deploy flow.',
    '- `ik release merge-dev` — merge the dev branch into every release branch.',
    '- `ik audit` — audit packages against `infra-kit.config.ts` rules.',
    '- `ik doctor` — check gh / doppler / aws / rtk install + auth and repo setup.',
    '- `ik init` — (re)install shell integration and regenerate these agent-instruction files.',
    '',
    '## Conventions',
    '',
    '- Tickets are prefixed by area: `[FE]` frontend, `[BE]` backend, `[DO]` DevOps/infra, `[APP]` mobile app, `[IDEA]` proposal, `[ROOT]` cross-cutting. Pick the single dominant area.',
    '- Environment variables are managed through Doppler via `ik env-load` — never commit secrets.',
  ].join('\n')
}

const assertNotSymlink = (filePath: string): void => {
  if (fs.existsSync(filePath) && fs.lstatSync(filePath).isSymbolicLink()) {
    throw new Error(`Refusing to write ${filePath} because the destination is a symlink`)
  }
}

/** Copy a file to a timestamped `<file>.backup.<timestamp>` sibling. */
const backupFile = (filePath: string): void => {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-')

  fs.copyFileSync(filePath, `${filePath}.backup.${stamp}`)
}

/**
 * Write `nextContent` to `filePath` with OMC-style safety: refuse symlinks,
 * back up the prior file with a timestamp before overwriting, and skip the
 * write entirely when nothing changed (keeps re-runs churn-free).
 */
const writeManaged = (filePath: string, nextContent: string): WriteAction => {
  assertNotSymlink(filePath)

  const existed = fs.existsSync(filePath)
  const previous = existed ? fs.readFileSync(filePath, 'utf-8') : null

  if (previous === nextContent) return 'unchanged'

  if (existed) backupFile(filePath)

  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, nextContent, 'utf-8')

  return existed ? 'updated' : 'created'
}

const readOr = (filePath: string, fallback: string): string => {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : fallback
}

const assertBlockPresent = (filePath: string, start: string, end: string): void => {
  const content = fs.readFileSync(filePath, 'utf-8')

  if (!hasManagedBlock(content, start, end)) {
    throw new Error(`Post-write validation failed: managed block missing from ${filePath}`)
  }
}

/**
 * Migrate a legacy `AGENTS.md` now that the guidance lives solely in `CLAUDE.md`.
 * Strips the infra-kit managed block, then asymmetrically:
 * - no infra-kit block at all (hand-authored, not ours) → leave untouched (`unchanged`),
 * - file was purely generated (nothing but whitespace remains) → back up + delete (`removed`),
 * - hand-authored content surrounds the block → back up + write the block-free remainder (`updated`).
 * Every destructive path leaves a timestamped `.backup.` first.
 */
const migrateLegacyAgentsFile = (agentsPath: string): WriteAction => {
  if (!fs.existsSync(agentsPath)) return 'unchanged'

  assertNotSymlink(agentsPath)

  const content = fs.readFileSync(agentsPath, 'utf-8')
  const stripped = removeManagedBlock(content, AGENTS_MARKER_START, AGENTS_MARKER_END)

  if (stripped === null) return 'unchanged'

  if (stripped.trim() === '') {
    backupFile(agentsPath)
    fs.rmSync(agentsPath)

    return 'removed'
  }

  return writeManaged(agentsPath, stripped)
}

/**
 * Generate (or refresh) the repo agent-instruction guidance, now hosted solely in
 * `CLAUDE.md` (preserving hand-authored content outside the markers). Also migrates
 * legacy setups — stripping the old `@AGENTS.md` import region from `CLAUDE.md` and
 * backing up/removing a now-redundant `AGENTS.md`. Repo-gated: a no-op outside an
 * infra-kit repo. Idempotent (within a CLI version) and non-destructive.
 *
 * @example
 * await writeAgentFiles()
 * // INFO: Agent-instruction files synced (infra-kit 0.1.105)
 */
export const writeAgentFiles = async (): Promise<WriteAgentFilesResult> => {
  let mainConfigPath: string

  try {
    mainConfigPath = (await getInfraKitConfigPaths()).main
  } catch {
    logger.info('Skipped agent-instruction files — not inside an infra-kit repo')

    return { skipped: true, root: null, written: [] }
  }

  if (!fs.existsSync(mainConfigPath)) {
    logger.info('Skipped agent-instruction files — no infra-kit.json at the repo root')

    return { skipped: true, root: null, written: [] }
  }

  const root = path.dirname(mainConfigPath)
  const version = packageJson.version
  const body = buildAgentsBody(version)

  const agentsPath = path.join(root, AGENTS_FILE)
  const claudePath = path.join(root, CLAUDE_FILE)

  // CLAUDE.md now hosts the full guidance body. Strip the legacy `@AGENTS.md`
  // import region first (if present), then upsert the body under the begin/end
  // markers — disjoint marker pairs, so the two operations never collide.
  let claudeContent = readOr(claudePath, '')

  claudeContent = removeManagedBlock(claudeContent, AGENTS_IMPORT_START, AGENTS_IMPORT_END) ?? claudeContent
  claudeContent = upsertManagedBlock({
    content: claudeContent,
    body,
    startMarker: AGENTS_MARKER_START,
    endMarker: AGENTS_MARKER_END,
    placement: 'replace-in-place',
  })

  // CLAUDE.md is the only file we manage. A legacy AGENTS.md is migrated away.
  const written: AgentFileWrite[] = [
    { path: claudePath, action: writeManaged(claudePath, claudeContent) },
    { path: agentsPath, action: migrateLegacyAgentsFile(agentsPath) },
  ]

  assertBlockPresent(claudePath, AGENTS_MARKER_START, AGENTS_MARKER_END)

  for (const file of written) {
    // Always report CLAUDE.md; only mention a migrated file when it actually changed.
    if (file.action === 'unchanged' && file.path !== claudePath) continue

    logger.info(`  ${file.action.padEnd(9)} ${path.relative(root, file.path)}`)
  }

  logger.info(`Agent-instruction files synced (infra-kit ${version})`)

  return { skipped: false, root, written }
}
